PORTFOLIO_LINKS = {
    "github": "https://github.com/jay-powerbi",
    "linkedin": "https://www.linkedin.com/in/jiayishi-bi/",
    "email": "jiayishi2@gmail.com",
}


PORTFOLIO_EXPERIENCE = [
    {
        "id": "freelance",
        "role": "Senior Power BI Developer",
        "company": "Freelance",
        "location": "Remote",
        "dates": "Feb 2024 – Present",
        "highlights": [
            "Designed and deployed custom Power BI, Tableau, and SQL dashboards with advanced DAX calculations and Power Query transformations for enterprise clients.",
            "Built ETL pipelines using SSIS and SQL scripts to integrate disparate data sources into unified reporting models (Star/Snowflake schemas).",
            "Collaborated with stakeholders to gather requirements and delivered paginated reports and geospatial KPI dashboards aligned with business goals.",
            "Optimized SQL queries and data models, improving report performance and data retrieval speed by up to 40%.",
        ],
    },
    {
        "id": "freedom-mortgage",
        "role": "Business Intelligence Developer",
        "company": "Freedom Mortgage Inc.",
        "location": "Cherry Hill, NJ",
        "dates": "Jan 2018 – Dec 2023",
        "highlights": [
            "Led end-to-end development of Power BI and SQL-based dashboards providing executive-level KPI insights and real-time business reporting.",
            "Implemented SQL indexing, query optimization, and ETL best practices, significantly reducing data processing times across enterprise pipelines.",
            "Mentored junior BI developers on Power BI best practices, DAX authoring, and Agile delivery workflows.",
            "Partnered with cross-functional teams to define data models and reporting standards; managed deployment, security access, and production migrations.",
            "Received the company's prestigious 'High Flyer' award for outstanding contributions to organizational BI capabilities.",
        ],
    },
    {
        "id": "mountinvest",
        "role": "Data Analyst / Tableau Developer",
        "company": "American Mountinvest Holding Company",
        "location": "Bala Cynwyd, PA",
        "dates": "Oct 2016 – Dec 2017",
        "highlights": [
            "Developed real-time Tableau and WebFocus dashboards using SQL-driven data models, enabling data-driven decision-making across business units.",
            "Automated routine reporting with SQL scripts, reducing manual effort and improving data accuracy and accessibility.",
        ],
    },
    {
        "id": "tmg-health",
        "role": "Business Intelligence Developer",
        "company": "TMG Health Inc.",
        "location": "Jessup, PA",
        "dates": "Jul 2015 – Oct 2016",
        "highlights": [
            "Led data mining and ETL initiatives using SQL to extract, transform, and load large volumes of healthcare data for stakeholder reporting.",
            "Collaborated with UAT and development teams to validate SQL-based solutions, ensuring data accuracy and production reliability.",
        ],
    },
]


PORTFOLIO_PROJECTS = [
    {
        "slug": "insurance",
        "title": "Insurance Claims Performance Dashboard for Smarter Decisions",
        "color": "#58A6FF",
        "icon": "IF",
        "preview_image": "images/projects/insurance-executive-summary.png",
        "tags": ["Power BI", "DAX", "Geospatial", "KPI"],
        "summary": "An interactive Power BI dashboard that analyzes insurance claims performance across time, lines of business, claim types, and regions.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Empowering insurance leaders with data-driven insights to reduce claim cycle time, control costs, improve customer satisfaction, and prevent fraud.",
            "description": "This interactive Power BI dashboard analyzes insurance claims performance across time, lines of business, claim types, and regions — so leaders can enhance operational efficiency, control costs, and strengthen risk management without waiting on manual reports.",
            "hero_image": "images/projects/insurance-executive-summary.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/insurance-claims-powerbi-dashboard"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Scattered claims data made it hard to monitor performance, control costs, detect fraud, and ensure timely resolution for policyholders.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "How are claims trending over time and by line of business?",
                            "Which claim types and regions have the highest cost?",
                            "How long does it take to close claims across different categories?",
                            "What is the denial rate and why are claims being denied?",
                            "Are there potential fraud patterns impacting losses?",
                        ],
                    },
                    "goal": "Provide a unified dashboard that delivers actionable insights to reduce claim cycle time, lower loss ratio, detect fraud, and improve customer satisfaction through data-driven decision making.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from claims data preparation and modeling to dashboard design and stakeholder delivery.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate claims insights and a dashboard leaders could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Standardized claim records, removed duplicates, and prepared data for analysis.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema with optimized relationships.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for cost, cycle time, denial rate, and fraud indicators.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built interactive visuals with drill-throughs and bookmarks.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "An executive-friendly dashboard with KPI scorecards, claims trends, status breakdowns, line-of-business analysis, regional cycle time maps, and fraud savings—designed for clarity at a glance.",
                    "gallery": [
                        "images/projects/insurance-executive-summary.png",
                        "images/projects/insurance-fraud-risk-assessment.png",
                        "images/projects/insurance-claims-operations.png",
                        "images/projects/insurance-executive-recommendations.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Leaders can now find answers in seconds instead of waiting for manual claims reports.",
                    "insights": [
                        {"icon": "trend", "text": "Total incurred increased 10.9% YoY"},
                        {"icon": "trend", "text": "Claim cycle time reduced by 12.3% YoY"},
                        {"icon": "people", "text": "Auto claims have the highest incurred cost"},
                        {"icon": "percent", "text": "Denial rate is 7.4%, driven by exclusions"},
                        {"icon": "trend", "text": "Fraud savings increased 11.3% YoY"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "Automated narrative highlights surface the most important claims performance patterns for leadership review.",
                    "executive_summary": [
                        "Total claims increased 8.7% to 125.8K.",
                        "Total incurred reached $312.7M with $248.3M paid.",
                        "Auto line is the highest cost at $98.7M.",
                        "Average claim cycle time is 18.6 days with a 7.4% denial rate.",
                        "Fraud detection saved $12.6M.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Claims Manager",
                            "problem": "Need to monitor cycle time and claim volume across lines of business.",
                            "solution": "Cycle time KPIs and claims trend views to prioritize resources.",
                        },
                        {
                            "stakeholder": "Finance Director",
                            "problem": "Must track incurred vs paid trends to control costs.",
                            "solution": "Incurred and paid amount analysis with line-of-business breakdown.",
                        },
                        {
                            "stakeholder": "Fraud Analyst",
                            "problem": "Need to identify suspicious patterns and high-risk claims.",
                            "solution": "Fraud indicators and risk segmentation views to increase savings.",
                        },
                        {
                            "stakeholder": "Operations Manager",
                            "problem": "Must analyze bottlenecks in the claims workflow.",
                            "solution": "Status breakdown and cycle time by category to adjust workflow.",
                        },
                        {
                            "stakeholder": "Customer Service Lead",
                            "problem": "Need faster claim resolution to improve policyholder experience.",
                            "solution": "Cycle time tracking and status views to reduce resolution time.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard saves time, improves claims efficiency, and gives leadership a shared view of performance and risk.",
                    "checklist": [
                        "Reduced average claim cycle time by 12.3%",
                        "Lowered claim denial rate by 0.6%",
                        "Improved fraud detection and savings by 11.3%",
                        "Enhanced customer satisfaction with faster resolution",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform complex insurance data into clear, decision-ready analytics.",
                    "bullets": [
                        "Understanding business context before building visuals leads to better adoption.",
                        "Strong data modeling and DAX are what turn raw claims data into actionable insights.",
                        "Dashboard design is about storytelling—not just displaying numbers.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 2M+ claim records",
                        "Built Star Schema data model",
                        "Created 50+ DAX measures and KPIs",
                        "Optimized Power BI performance",
                        "Integrated multiple data sources",
                        "Designed interactive drill-through pages",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "Kaggle – Insurance Claims Fraud Detection Dataset",
                    "datasets": [],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "healthcare",
        "title": "Healthcare Executive Analytics Dashboard for Smarter Decisions",
        "color": "#14B8A6",
        "icon": "HC",
        "preview_image": "images/projects/healthcare-executive-summary.png",
        "tags": ["Power BI", "DAX", "Healthcare KPIs"],
        "summary": "An interactive Power BI dashboard that helps healthcare leaders monitor patient volume, clinical operations, billing performance, and insurance mix.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Empowering healthcare leaders with unified visibility into patient demand, clinical operations, and financial performance.",
            "description": "This interactive Power BI dashboard analyzes patient admissions, medical conditions, length of stay, billing trends, and insurance coverage — so hospital leaders can improve capacity planning, revenue management, and patient outcomes without waiting on manual reports.",
            "hero_image": "images/projects/healthcare-executive-summary.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/healthcare-executive-analytics-powerbi-dashboard"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Healthcare leaders lacked a unified view of patient volume, clinical workload, billing performance, and payer mix — making it hard to plan capacity and control costs.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "How are patient admissions trending over time and by admission type?",
                            "Which medical conditions drive the highest patient volume and length of stay?",
                            "What is the hospital's billing performance by condition, provider, and month?",
                            "How is patient demand distributed across age groups and insurance payers?",
                            "Where can operations improve discharge efficiency and resource allocation?",
                        ],
                    },
                    "goal": "Provide an executive analytics dashboard that enables healthcare teams to improve operational efficiency, financial performance, and patient care planning.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from healthcare data preparation and modeling to dashboard design and stakeholder delivery.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate healthcare insights and a dashboard leaders could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Standardized patient, admission, billing, and insurance fields and prepared refreshable healthcare datasets.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema connecting patients, conditions, admissions, providers, and calendar dimensions.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for patient volume, average age, length of stay, billing totals, and emergency admissions.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built executive, financial, and clinical operations views with filters, trend charts, and recommendation summaries.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "An executive-friendly dashboard with KPI scorecards, admission trends, condition analysis, billing performance, clinical operations, and strategic recommendations.",
                    "gallery": [
                        "images/projects/healthcare-executive-summary.png",
                        "images/projects/healthcare-financial-analysis.png",
                        "images/projects/healthcare-clinical-operations.png",
                        "images/projects/healthcare-executive-recommendations.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Leaders can now find answers in seconds instead of waiting for manual operational reports.",
                    "insights": [
                        {"icon": "people", "text": "Hospital served 56K patients with stable monthly admissions"},
                        {"icon": "trend", "text": "Total billing reached $1.4B with $25.5K average billing per patient"},
                        {"icon": "percent", "text": "Chronic conditions such as Diabetes and Hypertension drive highest billing"},
                        {"icon": "globe", "text": "Emergency admissions totaled 18K, indicating sustained acute care demand"},
                        {"icon": "trend", "text": "Average length of stay is 15.5 days across major conditions"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "Automated narrative highlights surface the most important healthcare performance patterns for leadership review.",
                    "executive_summary": [
                        "The hospital served over 56K patients with admissions averaging approximately 4.6K per month.",
                        "Average patient age is 52, with the majority of patients in the 36–75 age groups.",
                        "Total billing reached approximately $1.4B with diversified payer mix across major insurers.",
                        "Chronic diseases such as Arthritis, Diabetes, and Hypertension account for the largest share of visits.",
                        "Emergency admissions totaled 18K with an average length of stay of 15.5 days.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Hospital Executives",
                            "problem": "Need a unified view of patient demand, revenue, and operational performance.",
                            "solution": "Executive overview with admissions trends, KPI scorecards, and strategic recommendations.",
                        },
                        {
                            "stakeholder": "Finance Leaders",
                            "problem": "Must monitor billing performance and payer concentration risk.",
                            "solution": "Financial analysis by condition, month, insurance provider, and top billing entities.",
                        },
                        {
                            "stakeholder": "Clinical Operations",
                            "problem": "Need to understand length of stay, test results, and admission mix.",
                            "solution": "Clinical operations dashboard with LOS, medication utilization, and age group analysis.",
                        },
                        {
                            "stakeholder": "Capacity Planners",
                            "problem": "Must forecast demand across admission types and conditions.",
                            "solution": "Monthly admission trends and condition-level volume breakdowns.",
                        },
                        {
                            "stakeholder": "Payer Relations",
                            "problem": "Need visibility into insurance provider distribution and reimbursement patterns.",
                            "solution": "Insurance mix analysis across executive and financial views.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard improves planning, financial oversight, and gives leadership a shared view of healthcare performance.",
                    "checklist": [
                        "Enabled faster capacity and staffing decisions",
                        "Improved visibility into billing and payer mix",
                        "Supported chronic disease management planning",
                        "Reduced reliance on manual operational reporting",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform complex healthcare data into clear, decision-ready analytics.",
                    "bullets": [
                        "Healthcare analytics requires connecting clinical, operational, and financial metrics in one model.",
                        "Executive dashboards must balance patient outcomes with revenue and capacity insights.",
                        "Clear segmentation by condition, payer, and admission type drives actionable recommendations.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 56K+ patient records",
                        "Built Star Schema data model",
                        "Created 40+ DAX measures and KPIs",
                        "Designed multi-page executive dashboard",
                        "Integrated admission, billing, and clinical datasets",
                        "Built interactive filters for gender, date, condition, and age group",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "Healthcare Patient Records Dataset",
                    "datasets": [],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "retail",
        "title": "Retail Performance Dashboard for Smarter Decisions",
        "color": "#5DCAA5",
        "icon": "RS",
        "preview_image": "images/projects/retail-sales-executive.png",
        "tags": ["Star Schema", "DAX", "Bookmarks"],
        "summary": "An interactive Power BI dashboard that helps retail executives track sales, profit, and performance across categories, regions, and segments.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "An end-to-end Power BI solution that turns retail data into actionable business insights.",
            "description": "This interactive dashboard gives retail executives a single source of truth for sales, profit, orders, and regional performance — so they can spot trends, compare categories, and act on growth opportunities without waiting on manual reports.",
            "hero_image": "images/projects/retail-sales-executive.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/retail-sales-powerbi-dashboard/tree/main"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Retail executives lacked a unified view of sales, profit, categories, and regions — making it hard to spot growth drivers and underperforming areas.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "Which categories and sub-categories drive the most sales and profit?",
                            "Which regions and customer segments are underperforming?",
                            "How are order volume, margin, and return rate trending over time?",
                            "Are shipping modes and promotions actually effective?",
                        ],
                    },
                    "goal": "Provide a comprehensive retail performance dashboard for faster, data-driven decisions.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from retail data preparation and modeling to dashboard design and stakeholder delivery.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate retail insights and a dashboard executives could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Removed duplicates, standardized product and region fields, and prepared refreshable sales datasets.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema connecting sales, customers, products, regions, and calendar dimensions.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for sales, profit, margin, orders, average order value, and return rate.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built interactive visuals with maps, drill-through pages, bookmarks, and executive-friendly layouts.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "An executive-friendly dashboard with KPI scorecards, sales trends, category analysis, profit by sub-category, regional maps, and key metrics vs last year—designed for clarity at a glance.",
                    "gallery": [
                        "images/projects/retail-sales-executive.png",
                        "images/projects/retail-geographic-analysis.png",
                        "images/projects/retail-product-performance.png",
                        "images/projects/retail-customer-analysis.png",
                        "images/projects/retail-ai-insights-summary.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Executives can now find answers in seconds instead of waiting for manual reports.",
                    "insights": [
                        {"icon": "trend", "text": "Technology is the top revenue driver"},
                        {"icon": "percent", "text": "Phones is the most profitable sub-category"},
                        {"icon": "globe", "text": "West region leads in total sales"},
                        {"icon": "people", "text": "Corporate segment has the highest average order value"},
                        {"icon": "trend", "text": "Return rate decreased 0.6% YoY"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "Automated narrative highlights surface the most important retail performance patterns for leadership review.",
                    "executive_summary": [
                        "Total sales increased 12.6% YoY to $2.31M.",
                        "Total profit grew 15.3% YoY to $286.4K.",
                        "Technology category drives the highest revenue.",
                        "Phones is the most profitable sub-category.",
                        "West region leads in sales performance.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Executive Team / C-Level",
                            "problem": "Need a high-level overview of sales, profit, and growth trends.",
                            "solution": "Executive dashboard with KPI cards and summary metrics.",
                        },
                        {
                            "stakeholder": "Sales Manager",
                            "problem": "Track team and category performance; identify underperforming areas.",
                            "solution": "Sales by category, region drill-down, and trend analysis.",
                        },
                        {
                            "stakeholder": "Category Manager",
                            "problem": "Compare sub-category profit and sales contribution.",
                            "solution": "Profit by sub-category and category performance views.",
                        },
                        {
                            "stakeholder": "Marketing Team",
                            "problem": "Measure segment performance and promotion effectiveness.",
                            "solution": "Customer segmentation views and segment KPI analysis.",
                        },
                        {
                            "stakeholder": "Operations",
                            "problem": "Monitor order volume, return rate, and shipping performance.",
                            "solution": "Order trends, return rate KPIs, and ship mode analysis.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard saves time, improves planning, and gives leadership a shared view of retail performance.",
                    "checklist": [
                        "Increased profit by 15.3% YoY",
                        "Improved decision speed",
                        "Reduced manual reporting time by 70%",
                        "Provided a single source of truth for retail performance",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform complex retail data into clear, decision-ready analytics.",
                    "bullets": [
                        "Understanding business context before building visuals leads to better adoption.",
                        "Strong DAX and data modeling turn raw transactions into actionable KPIs.",
                        "Storytelling and layout matter as much as the underlying data.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 1M+ retail transactions",
                        "Built Star Schema data model",
                        "Created 40+ DAX measures and KPIs",
                        "Optimized Power BI performance",
                        "Integrated multiple data sources",
                        "Designed interactive drill-through pages",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "Kaggle Online Retail Sales Dataset",
                    "datasets": ["December 2009 – December 2011"],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "supply-chain",
        "title": "Supply Chain Performance Dashboard for Data-Driven Decisions",
        "color": "#EF9F27",
        "icon": "SC",
        "preview_image": "images/projects/supply-chain-executive-summary.png",
        "tags": ["Power Query", "DAX", "Scorecard"],
        "summary": "An interactive Power BI dashboard that analyzes supply chain performance across suppliers, inventory, orders, and logistics.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Empowering supply chain leaders with end-to-end visibility to optimize inventory, reduce cost, improve delivery performance, and mitigate risks.",
            "description": "This interactive Power BI dashboard analyzes supply chain performance across suppliers, inventory, orders, and logistics — so leaders can drive operational excellence without waiting on manual reports.",
            "hero_image": "images/projects/supply-chain-executive-summary.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/supply-chain-powerbi-dashboard"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Supply chain leaders lack real-time visibility across suppliers, inventory, orders, and logistics — making it hard to control cost, ensure service level, and respond to disruptions.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "Which suppliers are not meeting delivery commitments?",
                            "What factors are driving supply chain cost increases?",
                            "Where are inventory stockouts and overstock risks greatest?",
                            "Are on-time delivery and lead time improving over time?",
                        ],
                    },
                    "goal": "Provide an end-to-end dashboard that enables supply chain teams to improve performance, reduce cost, optimize inventory, and enhance customer service.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I was responsible for end-to-end dashboard development and data modeling.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate supply chain insights and a dashboard operations teams could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Removed duplicates, standardized supplier and product fields, and prepared refreshable supply chain datasets.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema connecting orders, inventory, suppliers, logistics, and calendar dimensions.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for supply chain cost, on-time delivery, lead time, inventory turnover, and stockout rate.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built interactive visuals with supplier scorecards, regional maps, drill-through pages, and executive-friendly layouts.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "An executive-friendly dashboard that brings all critical supply chain metrics into one place.",
                    "gallery": [
                        "images/projects/supply-chain-executive-summary.png",
                        "images/projects/supply-chain-supplier-logistics.png",
                        "images/projects/supply-chain-kpi-overview.png",
                        "images/projects/supply-chain-product-quality.png",
                        "images/projects/supply-chain-insights-summary.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Leaders can now find answers in seconds instead of waiting for manual operational reports.",
                    "insights": [
                        {"icon": "trend", "text": "On-time delivery improved 4.5% YoY"},
                        {"icon": "percent", "text": "Inventory turnover increased to 6.2x"},
                        {"icon": "trend", "text": "Stockout rate reduced to 2.1%"},
                        {"icon": "globe", "text": "Ocean freight has the lowest cost per unit"},
                        {"icon": "trend", "text": "Lead time reduced to 5.6 days"},
                        {"icon": "trend", "text": "Supply chain cost decreased 8.7% YoY"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "The dashboard automatically summarizes the most important business insights for executives.",
                    "executive_summary": [
                        "Total supply chain cost decreased 8.7% YoY to $4.82M.",
                        "On-time delivery improved 4.5% YoY to 92.6%.",
                        "Inventory turnover increased to 6.2x with stockout rate at 2.1%.",
                        "Lead time reduced to 5.6 days across key suppliers.",
                        "Ocean freight delivers the lowest cost per unit among ship modes.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Supply Chain Director",
                            "problem": "Need end-to-end visibility across cost, delivery, and inventory performance.",
                            "solution": "Executive dashboard with KPI cards and supply chain summary metrics.",
                        },
                        {
                            "stakeholder": "Procurement Manager",
                            "problem": "Must identify suppliers missing delivery commitments and cost targets.",
                            "solution": "Supplier scorecards and delivery commitment tracking views.",
                        },
                        {
                            "stakeholder": "Inventory Manager",
                            "problem": "Track stockout risk, turnover, and overstock by category.",
                            "solution": "Inventory turnover KPIs and stockout rate analysis by product.",
                        },
                        {
                            "stakeholder": "Logistics Manager",
                            "problem": "Compare ship modes, routes, and lead time bottlenecks.",
                            "solution": "Logistics performance views and on-time delivery by region.",
                        },
                        {
                            "stakeholder": "Finance Manager",
                            "problem": "Monitor supply chain cost trends and cost drivers over time.",
                            "solution": "Cost trend analysis and cost-by-category breakdown views.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard helped the business save time, reduce cost, and improve service level.",
                    "checklist": [
                        "Reduced supply chain cost by 8.7%",
                        "Improved on-time delivery by 4.3%",
                        "Reduced lead time to 5.6 days",
                        "Improved inventory turnover to 6.2x",
                        "Reduced manual reporting time by 70%",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform complex supply chain data into clear, decision-ready analytics.",
                    "bullets": [
                        "End-to-end supply chain visibility requires connecting orders, inventory, and logistics in one model.",
                        "Strong DAX and data modeling turn operational data into actionable KPIs leaders trust.",
                        "Dashboard design is about storytelling—not just displaying metrics.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 10M+ supply chain records",
                        "Built Star Schema data model",
                        "Created 50+ DAX measures and KPIs",
                        "Optimized Power BI performance",
                        "Integrated multiple data sources",
                        "Designed interactive drill-through pages",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "Kaggle Supply Chain Dataset",
                    "datasets": [],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "zillow",
        "title": "US Housing Price Trends & Market Insights for Smarter Decisions",
        "color": "#AFA9EC",
        "icon": "ZH",
        "preview_image": "images/projects/zillow-housing-executive-summary.png",
        "tags": ["Maps", "DAX", "Trends"],
        "summary": "An interactive Power BI dashboard that empowers real estate professionals with data-driven housing market insights.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "An end-to-end Power BI solution that turns housing market data into actionable business insights.",
            "description": "This interactive dashboard empowers real estate professionals, investors, and analysts with a single source of truth for home prices, sales activity, inventory, affordability, and regional trends — so they can compare markets and act on opportunities without waiting on manual reports.",
            "hero_image": "images/projects/zillow-housing-executive-summary.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/us-housing-market-powerbi-dashboard"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Real estate professionals lacked a unified view of housing prices, inventory, and regional trends — making it hard to compare markets and spot opportunities.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "Which metros and states show the strongest price growth?",
                            "How are inventory and days on market trending over time?",
                            "Which property types drive the most sales volume?",
                            "Where are regional price differences most significant?",
                        ],
                    },
                    "goal": "Provide a comprehensive market intelligence dashboard for faster, data-driven real estate decisions.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from housing data preparation and modeling to dashboard design and stakeholder delivery.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate housing market insights and a dashboard leaders could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Standardized listings, census fields, and regional dimensions from multiple housing data providers.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema connecting sales, geography, property type, and calendar dimensions.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for median price, price per sq ft, inventory, days on market, and affordability.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built interactive visuals with maps, trend charts, drill-through pages, and executive-friendly layouts.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "A clean, executive-friendly dashboard with KPI scorecards, price trends, property type analysis, state comparisons, regional maps, and market summary tables—designed for clarity at a glance.",
                    "gallery": [
                        "images/projects/zillow-housing-executive-summary.png",
                        "images/projects/zillow-housing-state-comparison.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Leaders can now find answers in seconds instead of waiting for manual market reports.",
                    "insights": [
                        {"icon": "trend", "text": "Median home price increased 7.2% YoY"},
                        {"icon": "percent", "text": "Inventory declined 15.6% YoY"},
                        {"icon": "globe", "text": "California leads with $582K median price"},
                        {"icon": "people", "text": "Single family homes drive 63.1% of sales"},
                        {"icon": "trend", "text": "West region shows strongest growth at 9.8%"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "Automated narrative highlights surface the most important housing market patterns for leadership review.",
                    "executive_summary": [
                        "Median home price reached $412K, up 7.2% YoY.",
                        "West region leads growth at 9.8% YoY.",
                        "California has the highest median price at $582K.",
                        "Single family homes account for 63.1% of total sales.",
                        "Inventory fell to 2.6 months, indicating a seller's market.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Real Estate Investors",
                            "problem": "Need to identify high-growth markets and price momentum quickly.",
                            "solution": "Regional trend analysis and YoY growth comparison views.",
                        },
                        {
                            "stakeholder": "Realtors / Agents",
                            "problem": "Track local inventory, days on market, and pricing for client guidance.",
                            "solution": "Metro-level maps and inventory KPI dashboards.",
                        },
                        {
                            "stakeholder": "Lenders & Mortgage Analysts",
                            "problem": "Assess market risk and price stability across regions.",
                            "solution": "Median price trends, affordability index, and regional volatility indicators.",
                        },
                        {
                            "stakeholder": "Property Developers",
                            "problem": "Compare demand signals across property types and geographies.",
                            "solution": "Sales by property type and state-level price comparisons.",
                        },
                        {
                            "stakeholder": "Market Researchers",
                            "problem": "Monitor macro housing trends without manual data pulls.",
                            "solution": "Time-series price trends and executive summary metrics.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard saves time, improves market analysis, and gives leadership a shared view of housing performance.",
                    "checklist": [
                        "Reduced manual reporting time by 70%",
                        "Enabled faster market analysis",
                        "Improved regional comparison capability",
                        "Supported data-driven investment decisions",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform complex housing data into clear, decision-ready analytics.",
                    "bullets": [
                        "Understanding market questions before building visuals leads to better adoption.",
                        "Strong DAX and data modeling are what make housing KPIs reliable at scale.",
                        "Maps and regional comparisons are essential for real estate storytelling.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 10M+ housing records",
                        "Built Star Schema data model",
                        "Created 30+ DAX measures and KPIs",
                        "Optimized Power BI performance",
                        "Integrated geospatial visualizations",
                        "Designed interactive drill-through pages",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "Zillow Home Value Index (ZHVI)",
                    "datasets": [],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "uber",
        "title": "NYC FHV Performance Dashboard for Data-Driven Decisions",
        "color": "#F0997B",
        "icon": "UB",
        "preview_image": "images/projects/uber-fhv-executive-summary.png",
        "tags": ["Power Query", "Maps", "DAX"],
        "summary": "An interactive Power BI dashboard that helps NYC Uber and FHV drivers, fleet operators, and analysts optimize earnings and understand city trends.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Empowering drivers, fleet operators, and analysts with real-time insights to improve earnings, optimize driving time, and understand city trends.",
            "description": "This interactive Power BI dashboard gives FHV stakeholders a single source of truth for trips, earnings, distance, and zone performance across NYC — so they can focus on high-demand hours, boroughs, and pickup zones without waiting on manual reports.",
            "hero_image": "images/projects/uber-fhv-executive-summary.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/nyc-fhv-powerbi-dashboard"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Drivers and operators lacked insight into demand, high-earning zones, and peak hours — making it hard to maximize earnings across NYC.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "Which hours and days generate the highest earnings?",
                            "Which pickup zones and boroughs drive the most trip volume?",
                            "How do airport trips compare to commuter and short trips?",
                            "Are trips, earnings, and distance improving over time?",
                        ],
                    },
                    "goal": "Provide a single dashboard that delivers actionable insights to help drivers and operators increase earnings and improve efficiency.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from TLC trip data preparation and modeling to dashboard design and stakeholder delivery.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate FHV insights and a dashboard operators could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Removed duplicates, standardized zone and borough fields, and prepared refreshable trip datasets.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema connecting trips, zones, boroughs, calendar, and trip type dimensions.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for trips, gross earnings, distance, trip time, and earnings per trip.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built interactive visuals with heatmaps, borough breakdowns, zone rankings, and drill-through detail.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "A dark-themed, operator-friendly dashboard with KPI scorecards, trip trends, borough analysis, top pickup zones, time-of-day heatmaps, and trip type performance—designed for clarity at a glance.",
                    "gallery": [
                        "images/projects/uber-fhv-executive-summary.png",
                        "images/projects/uber-fhv-performance.png",
                        "images/projects/uber-fhv-driver-pay.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Drivers and analysts can now find answers in seconds instead of waiting for manual trip reports.",
                    "insights": [
                        {"icon": "trend", "text": "Friday & Saturday nights generate the most earnings"},
                        {"icon": "percent", "text": "Airport trips have the highest earnings per trip ($54.32)"},
                        {"icon": "globe", "text": "JFK Airport is the top earning pickup zone ($18.7M)"},
                        {"icon": "people", "text": "Manhattan has the highest trip volume (36.8%)"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "Automated narrative highlights surface the most important FHV performance patterns for leadership review.",
                    "executive_summary": [
                        "Total trips increased 12.6% YoY to 5.21M, driving 15.3% growth in gross earnings to $213.4M.",
                        "Airport trips average $54.32 per trip, significantly higher than commuter ($38.21) and short trips ($21.15).",
                        "Peak earnings occur Friday/Saturday nights between 6 PM and 2 AM.",
                        "JFK Airport is the top earning pickup zone, contributing $18.7M in gross earnings.",
                        "Average earnings per trip reached $40.96, up 2.4% YoY.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Drivers",
                            "problem": "Need to know when and where to drive for maximum earnings.",
                            "solution": "Time-of-day heatmaps, top pickup zones, and borough demand views.",
                        },
                        {
                            "stakeholder": "Fleet Operators",
                            "problem": "Optimize fleet deployment across boroughs and trip types.",
                            "solution": "Borough breakdown, trip type performance, and trend analysis.",
                        },
                        {
                            "stakeholder": "Business Analysts",
                            "problem": "Monitor FHV market trends and earnings performance over time.",
                            "solution": "Trips over time charts and YoY KPI scorecards.",
                        },
                        {
                            "stakeholder": "City Planners",
                            "problem": "Understand geographic demand concentration across NYC zones.",
                            "solution": "Zone rankings and borough distribution analysis.",
                        },
                        {
                            "stakeholder": "Policy Makers",
                            "problem": "Assess FHV activity patterns for regulatory and planning decisions.",
                            "solution": "Executive summary metrics and regional trip volume views.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard improves earnings optimization, fleet efficiency, and gives stakeholders a shared view of FHV performance.",
                    "checklist": [
                        "Increased driver earnings by optimizing time and zones",
                        "Improved fleet utilization and operational efficiency",
                        "Reduced manual reporting time by 70%",
                        "Provided a single source of truth for FHV performance",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform large-scale transportation data into clear, decision-ready analytics.",
                    "bullets": [
                        "Understanding driver and operator questions before building visuals leads to better adoption.",
                        "Aggregating high-volume trip data requires careful modeling for dashboard performance.",
                        "Time-of-day and zone views are essential for FHV earnings storytelling.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 20M+ FHV trip records",
                        "Built Star Schema data model",
                        "Created 35+ DAX measures and KPIs",
                        "Optimized Power BI performance",
                        "Integrated TLC Lookup Tables",
                        "Designed interactive drill-through pages",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "NYC TLC For-Hire Vehicle (FHV) Trip Records",
                    "datasets": ["January–March 2026"],
                },
                {
                    "icon": "database",
                    "label": "NYC Taxi Zone Lookup Table",
                    "datasets": [],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
]


PORTFOLIO_PROJECT_MAP = {project["slug"]: project for project in PORTFOLIO_PROJECTS}
