PORTFOLIO_LINKS = {
    "github": "https://github.com/jay-powerbi",
    "linkedin": "https://www.linkedin.com/in/jiayishi-bi/",
    "email": "jiayishi2@gmail.com",
}


PORTFOLIO_EXPERIENCE = [
    {
        "id": "freelance",
        "role": "Power BI Developer / BI Consultant",
        "company": "Freelance",
        "location": "Remote",
        "dates": "Feb 2024 – Present",
        "highlights": [
            "Build Power BI and Tableau dashboards by first clarifying the business problem, intended users, and decisions the report needs to support.",
            "Transform and validate source data with Power Query and SQL, define reporting logic, and organize data into analysis-ready models based on project needs.",
            "Develop DAX measures, KPI views, drill-through experiences, and geospatial analysis to help users move from high-level trends to underlying drivers.",
            "Collaborate with stakeholders to refine requirements and translate business questions into practical dashboard workflows and reporting outputs.",
            "Review query and model design to improve report responsiveness, usability, and maintainability.",
        ],
    },
    {
        "id": "freedom-mortgage",
        "role": "Business Intelligence Developer",
        "company": "Freedom Mortgage Inc.",
        "location": "Cherry Hill, NJ",
        "dates": "Jan 2018 – Dec 2023",
        "highlights": [
            "Led end-to-end development of Power BI and SQL-based dashboards providing executive-level KPI insights and real-time business reporting.",
            "Implemented SQL indexing, query optimization, and ETL best practices, significantly reducing data processing times across enterprise pipelines.",
            "Mentored junior BI developers on Power BI best practices, DAX authoring, and Agile delivery workflows.",
            "Partnered with cross-functional teams to define data models and reporting standards; managed deployment, security access, and production migrations.",
            "Received the company's prestigious 'High Flyer' award for outstanding contributions to organizational BI capabilities.",
        ],
    },
    {
        "id": "mountinvest",
        "role": "Data Analyst / Tableau Developer",
        "company": "American Mountinvest Holding Company",
        "location": "Bala Cynwyd, PA",
        "dates": "Oct 2016 – Dec 2017",
        "highlights": [
            "Developed real-time Tableau and WebFocus dashboards using SQL-driven data models, enabling data-driven decision-making across business units.",
            "Automated routine reporting with SQL scripts, reducing manual effort and improving data accuracy and accessibility.",
        ],
    },
    {
        "id": "tmg-health",
        "role": "Business Intelligence Developer",
        "company": "TMG Health Inc.",
        "location": "Jessup, PA",
        "dates": "Jul 2015 – Oct 2016",
        "highlights": [
            "Led data mining and ETL initiatives using SQL to extract, transform, and load large volumes of healthcare data for stakeholder reporting.",
            "Collaborated with UAT and development teams to validate SQL-based solutions, ensuring data accuracy and production reliability.",
        ],
    },
]


PORTFOLIO_PROJECTS = [
    {
        "slug": "insurance",
        "title": "Insurance Claims Performance Dashboard for Smarter Decisions",
        "color": "#58A6FF",
        "icon": "IF",
        "preview_image": "images/projects/insurance-executive-summary.png",
        "tags": ["Power BI", "DAX", "Geospatial", "Kaggle"],
        "summary": "Helps users investigate unusual claim patterns, high-risk areas, and geographic concentrations that deserve closer review.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Helps users identify claim patterns and geographic areas that may require additional fraud investigation.",
            "description": "Large claim datasets can hide unusual patterns and high-risk concentrations. This fraud analytics experience moves users from high-level risk indicators into the underlying claim patterns and records for deeper investigation.",
            "hero_image": "images/projects/insurance-executive-summary.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/insurance-claims-powerbi-dashboard"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Large claim datasets can make it difficult to identify unusual patterns, high-risk claims, and geographic concentrations that deserve closer investigation.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "How are claims trending over time and by line of business?",
                            "Which claim types and regions have the highest cost?",
                            "How long does it take to close claims across different categories?",
                            "What is the denial rate and why are claims being denied?",
                            "Are there potential fraud patterns impacting losses?",
                        ],
                    },
                    "goal": "Provide an interactive fraud analytics experience that helps users move from high-level risk indicators into the claim patterns and records behind them.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from claims data preparation and modeling to dashboard design and stakeholder delivery.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate claims insights and a dashboard leaders could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Standardized claim records, removed duplicates, and prepared data for analysis.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema with optimized relationships.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for cost, cycle time, denial rate, and fraud indicators.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built interactive visuals with drill-throughs and bookmarks.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "An executive-friendly dashboard with KPI scorecards, claims trends, status breakdowns, line-of-business analysis, regional cycle time maps, and fraud savings—designed for clarity at a glance.",
                    "gallery": [
                        "images/projects/insurance-executive-summary.png",
                        "images/projects/insurance-fraud-risk-assessment.png",
                        "images/projects/insurance-claims-operations.png",
                        "images/projects/insurance-executive-recommendations.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Leaders can now find answers in seconds instead of waiting for manual claims reports.",
                    "insights": [
                        {"icon": "trend", "text": "Total incurred increased 10.9% YoY"},
                        {"icon": "trend", "text": "Claim cycle time reduced by 12.3% YoY"},
                        {"icon": "people", "text": "Auto claims have the highest incurred cost"},
                        {"icon": "percent", "text": "Denial rate is 7.4%, driven by exclusions"},
                        {"icon": "trend", "text": "Fraud savings increased 11.3% YoY"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "Automated narrative highlights surface the most important claims performance patterns for leadership review.",
                    "executive_summary": [
                        "Total claims increased 8.7% to 125.8K.",
                        "Total incurred reached $312.7M with $248.3M paid.",
                        "Auto line is the highest cost at $98.7M.",
                        "Average claim cycle time is 18.6 days with a 7.4% denial rate.",
                        "Fraud detection saved $12.6M.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Claims Manager",
                            "problem": "Need to monitor cycle time and claim volume across lines of business.",
                            "solution": "Cycle time KPIs and claims trend views to prioritize resources.",
                        },
                        {
                            "stakeholder": "Finance Director",
                            "problem": "Must track incurred vs paid trends to control costs.",
                            "solution": "Incurred and paid amount analysis with line-of-business breakdown.",
                        },
                        {
                            "stakeholder": "Fraud Analyst",
                            "problem": "Need to identify suspicious patterns and high-risk claims.",
                            "solution": "Fraud indicators and risk segmentation views to increase savings.",
                        },
                        {
                            "stakeholder": "Operations Manager",
                            "problem": "Must analyze bottlenecks in the claims workflow.",
                            "solution": "Status breakdown and cycle time by category to adjust workflow.",
                        },
                        {
                            "stakeholder": "Customer Service Lead",
                            "problem": "Need faster claim resolution to improve policyholder experience.",
                            "solution": "Cycle time tracking and status views to reduce resolution time.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard saves time, improves claims efficiency, and gives leadership a shared view of performance and risk.",
                    "checklist": [
                        "Reduced average claim cycle time by 12.3%",
                        "Lowered claim denial rate by 0.6%",
                        "Improved fraud detection and savings by 11.3%",
                        "Enhanced customer satisfaction with faster resolution",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform complex insurance data into clear, decision-ready analytics.",
                    "bullets": [
                        "Understanding business context before building visuals leads to better adoption.",
                        "Strong data modeling and DAX are what turn raw claims data into actionable insights.",
                        "Dashboard design is about storytelling—not just displaying numbers.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 2M+ claim records",
                        "Built Star Schema data model",
                        "Created 50+ DAX measures and KPIs",
                        "Optimized Power BI performance",
                        "Integrated multiple data sources",
                        "Designed interactive drill-through pages",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "Kaggle – Insurance Claims Fraud Detection Dataset",
                    "datasets": [],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "healthcare",
        "title": "Healthcare Executive Analytics Dashboard for Smarter Decisions",
        "color": "#14B8A6",
        "icon": "HC",
        "preview_image": "images/projects/healthcare-executive-summary.png",
        "tags": ["Power BI", "DAX", "Power Query", "Healthcare Patient Records"],
        "summary": "Transforms healthcare records into focused views of utilization, cost, and operational patterns for clearer investigation.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Helps users compare patient groups, explore utilization and cost patterns, and identify areas that may require deeper operational investigation.",
            "description": "Healthcare datasets can contain thousands of patient, admission, billing, and medical condition records, but raw records do not clearly reveal utilization, cost, or operational patterns. This healthcare analytics experience organizes those records into focused analytical views for operational investigation.",
            "hero_image": "images/projects/healthcare-executive-summary.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/healthcare-powerbi-dashboard"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Healthcare datasets can contain thousands of patient, admission, billing, and medical condition records, but raw records do not clearly reveal utilization, cost, or operational patterns.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "How are patient admissions trending over time and by admission type?",
                            "Which medical conditions drive the highest patient volume and length of stay?",
                            "What is the hospital's billing performance by condition, provider, and month?",
                            "How is patient demand distributed across age groups and insurance payers?",
                            "Where can operations improve discharge efficiency and resource allocation?",
                        ],
                    },
                    "goal": "Provide an interactive healthcare operational analytics experience that helps users explore utilization, cost, and patient-segment patterns.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from healthcare data preparation and modeling to dashboard design and stakeholder delivery.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate healthcare insights and a dashboard leaders could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Standardized patient, admission, billing, and insurance fields and prepared refreshable healthcare datasets.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema connecting patients, conditions, admissions, providers, and calendar dimensions.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for patient volume, average age, length of stay, billing totals, and emergency admissions.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built executive, financial, and clinical operations views with filters, trend charts, and recommendation summaries.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "An executive-friendly dashboard with KPI scorecards, admission trends, condition analysis, billing performance, clinical operations, and strategic recommendations.",
                    "gallery": [
                        "images/projects/healthcare-executive-summary.png",
                        "images/projects/healthcare-financial-analysis.png",
                        "images/projects/healthcare-clinical-operations.png",
                        "images/projects/healthcare-executive-recommendations.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Leaders can now find answers in seconds instead of waiting for manual operational reports.",
                    "insights": [
                        {"icon": "people", "text": "Hospital served 56K patients with stable monthly admissions"},
                        {"icon": "trend", "text": "Total billing reached $1.4B with $25.5K average billing per patient"},
                        {"icon": "percent", "text": "Chronic conditions such as Diabetes and Hypertension drive highest billing"},
                        {"icon": "globe", "text": "Emergency admissions totaled 18K, indicating sustained acute care demand"},
                        {"icon": "trend", "text": "Average length of stay is 15.5 days across major conditions"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "Automated narrative highlights surface the most important healthcare performance patterns for leadership review.",
                    "executive_summary": [
                        "The hospital served over 56K patients with admissions averaging approximately 4.6K per month.",
                        "Average patient age is 52, with the majority of patients in the 36–75 age groups.",
                        "Total billing reached approximately $1.4B with diversified payer mix across major insurers.",
                        "Chronic diseases such as Arthritis, Diabetes, and Hypertension account for the largest share of visits.",
                        "Emergency admissions totaled 18K with an average length of stay of 15.5 days.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Hospital Executives",
                            "problem": "Need a unified view of patient demand, revenue, and operational performance.",
                            "solution": "Executive overview with admissions trends, KPI scorecards, and strategic recommendations.",
                        },
                        {
                            "stakeholder": "Finance Leaders",
                            "problem": "Must monitor billing performance and payer concentration risk.",
                            "solution": "Financial analysis by condition, month, insurance provider, and top billing entities.",
                        },
                        {
                            "stakeholder": "Clinical Operations",
                            "problem": "Need to understand length of stay, test results, and admission mix.",
                            "solution": "Clinical operations dashboard with LOS, medication utilization, and age group analysis.",
                        },
                        {
                            "stakeholder": "Capacity Planners",
                            "problem": "Must forecast demand across admission types and conditions.",
                            "solution": "Monthly admission trends and condition-level volume breakdowns.",
                        },
                        {
                            "stakeholder": "Payer Relations",
                            "problem": "Need visibility into insurance provider distribution and reimbursement patterns.",
                            "solution": "Insurance mix analysis across executive and financial views.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard improves planning, financial oversight, and gives leadership a shared view of healthcare performance.",
                    "checklist": [
                        "Enabled faster capacity and staffing decisions",
                        "Improved visibility into billing and payer mix",
                        "Supported chronic disease management planning",
                        "Reduced reliance on manual operational reporting",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform complex healthcare data into clear, decision-ready analytics.",
                    "bullets": [
                        "Healthcare analytics requires connecting clinical, operational, and financial metrics in one model.",
                        "Executive dashboards must balance patient outcomes with revenue and capacity insights.",
                        "Clear segmentation by condition, payer, and admission type drives actionable recommendations.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 56K+ patient records",
                        "Built Star Schema data model",
                        "Created 40+ DAX measures and KPIs",
                        "Designed multi-page executive dashboard",
                        "Integrated admission, billing, and clinical datasets",
                        "Built interactive filters for gender, date, condition, and age group",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "Healthcare Patient Records Dataset",
                    "datasets": [],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "retail",
        "title": "Retail Performance Dashboard for Smarter Decisions",
        "color": "#5DCAA5",
        "icon": "RS",
        "preview_image": "images/projects/retail-sales-executive.png",
        "tags": ["Power BI", "Star Schema", "DAX", "Kaggle"],
        "summary": "Connects sales performance, customer behavior, and product profitability so users can explain what is driving results.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Helps users move from high-level performance changes to the products or customer segments contributing to those results.",
            "description": "Sales totals alone do not explain which products, customers, or segments are driving performance changes. This executive analytics experience connects sales performance, customer behavior, and product profitability through KPI and detailed analytical views.",
            "hero_image": "images/projects/retail-sales-executive.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/retail-sales-powerbi-dashboard/tree/main"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Sales totals alone do not explain which products, customers, or segments are driving performance changes.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "Which categories and sub-categories drive the most sales and profit?",
                            "Which regions and customer segments are underperforming?",
                            "How are order volume, margin, and return rate trending over time?",
                            "Are shipping modes and promotions actually effective?",
                        ],
                    },
                    "goal": "Provide an executive analytics experience that helps users investigate which products or customer segments contribute to performance changes.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from retail data preparation and modeling to dashboard design and stakeholder delivery.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate retail insights and a dashboard executives could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Removed duplicates, standardized product and region fields, and prepared refreshable sales datasets.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema connecting sales, customers, products, regions, and calendar dimensions.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for sales, profit, margin, orders, average order value, and return rate.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built interactive visuals with maps, drill-through pages, bookmarks, and executive-friendly layouts.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "An executive-friendly dashboard with KPI scorecards, sales trends, category analysis, profit by sub-category, regional maps, and key metrics vs last year—designed for clarity at a glance.",
                    "gallery": [
                        "images/projects/retail-sales-executive.png",
                        "images/projects/retail-geographic-analysis.png",
                        "images/projects/retail-product-performance.png",
                        "images/projects/retail-customer-analysis.png",
                        "images/projects/retail-ai-insights-summary.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Executives can now find answers in seconds instead of waiting for manual reports.",
                    "insights": [
                        {"icon": "trend", "text": "Technology is the top revenue driver"},
                        {"icon": "percent", "text": "Phones is the most profitable sub-category"},
                        {"icon": "globe", "text": "West region leads in total sales"},
                        {"icon": "people", "text": "Corporate segment has the highest average order value"},
                        {"icon": "trend", "text": "Return rate decreased 0.6% YoY"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "Automated narrative highlights surface the most important retail performance patterns for leadership review.",
                    "executive_summary": [
                        "Total sales increased 12.6% YoY to $2.31M.",
                        "Total profit grew 15.3% YoY to $286.4K.",
                        "Technology category drives the highest revenue.",
                        "Phones is the most profitable sub-category.",
                        "West region leads in sales performance.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Executive Team / C-Level",
                            "problem": "Need a high-level overview of sales, profit, and growth trends.",
                            "solution": "Executive dashboard with KPI cards and summary metrics.",
                        },
                        {
                            "stakeholder": "Sales Manager",
                            "problem": "Track team and category performance; identify underperforming areas.",
                            "solution": "Sales by category, region drill-down, and trend analysis.",
                        },
                        {
                            "stakeholder": "Category Manager",
                            "problem": "Compare sub-category profit and sales contribution.",
                            "solution": "Profit by sub-category and category performance views.",
                        },
                        {
                            "stakeholder": "Marketing Team",
                            "problem": "Measure segment performance and promotion effectiveness.",
                            "solution": "Customer segmentation views and segment KPI analysis.",
                        },
                        {
                            "stakeholder": "Operations",
                            "problem": "Monitor order volume, return rate, and shipping performance.",
                            "solution": "Order trends, return rate KPIs, and ship mode analysis.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard saves time, improves planning, and gives leadership a shared view of retail performance.",
                    "checklist": [
                        "Increased profit by 15.3% YoY",
                        "Improved decision speed",
                        "Reduced manual reporting time by 70%",
                        "Provided a single source of truth for retail performance",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform complex retail data into clear, decision-ready analytics.",
                    "bullets": [
                        "Understanding business context before building visuals leads to better adoption.",
                        "Strong DAX and data modeling turn raw transactions into actionable KPIs.",
                        "Storytelling and layout matter as much as the underlying data.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 1M+ retail transactions",
                        "Built Star Schema data model",
                        "Created 40+ DAX measures and KPIs",
                        "Optimized Power BI performance",
                        "Integrated multiple data sources",
                        "Designed interactive drill-through pages",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "Kaggle Online Retail Sales Dataset",
                    "datasets": ["December 2009 – December 2011"],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "supply-chain",
        "title": "Supply Chain Performance Dashboard for Data-Driven Decisions",
        "color": "#EF9F27",
        "icon": "SC",
        "preview_image": "images/projects/supply-chain-executive-summary.png",
        "tags": ["Power BI", "Power Query", "DAX", "Kaggle"],
        "summary": "Supports operational review of inventory movement, fill rate, and supplier reliability questions.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Helps users identify areas that may require further operational review and investigate potential fulfillment or supplier bottlenecks.",
            "description": "Inventory and supplier data can be difficult to interpret when teams need to understand movement, fulfillment performance, and supplier reliability. This operational analytics experience is designed around inventory movement, fill rate, and supplier performance questions.",
            "hero_image": "images/projects/supply-chain-executive-summary.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/supply-chain-powerbi-dashboard"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Inventory and supplier data can be difficult to interpret when operational teams need to understand movement, fulfillment performance, and supplier reliability.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "Which suppliers are not meeting delivery commitments?",
                            "What factors are driving supply chain cost increases?",
                            "Where are inventory stockouts and overstock risks greatest?",
                            "Are on-time delivery and lead time improving over time?",
                        ],
                    },
                    "goal": "Provide an operational analytics experience that helps users investigate inventory movement, fill rate, and supplier performance questions.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I was responsible for end-to-end dashboard development and data modeling.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate supply chain insights and a dashboard operations teams could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Removed duplicates, standardized supplier and product fields, and prepared refreshable supply chain datasets.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema connecting orders, inventory, suppliers, logistics, and calendar dimensions.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for supply chain cost, on-time delivery, lead time, inventory turnover, and stockout rate.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built interactive visuals with supplier scorecards, regional maps, drill-through pages, and executive-friendly layouts.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "An executive-friendly dashboard that brings all critical supply chain metrics into one place.",
                    "gallery": [
                        "images/projects/supply-chain-executive-summary.png",
                        "images/projects/supply-chain-supplier-logistics.png",
                        "images/projects/supply-chain-kpi-overview.png",
                        "images/projects/supply-chain-product-quality.png",
                        "images/projects/supply-chain-insights-summary.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Leaders can now find answers in seconds instead of waiting for manual operational reports.",
                    "insights": [
                        {"icon": "trend", "text": "On-time delivery improved 4.5% YoY"},
                        {"icon": "percent", "text": "Inventory turnover increased to 6.2x"},
                        {"icon": "trend", "text": "Stockout rate reduced to 2.1%"},
                        {"icon": "globe", "text": "Ocean freight has the lowest cost per unit"},
                        {"icon": "trend", "text": "Lead time reduced to 5.6 days"},
                        {"icon": "trend", "text": "Supply chain cost decreased 8.7% YoY"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "The dashboard automatically summarizes the most important business insights for executives.",
                    "executive_summary": [
                        "Total supply chain cost decreased 8.7% YoY to $4.82M.",
                        "On-time delivery improved 4.5% YoY to 92.6%.",
                        "Inventory turnover increased to 6.2x with stockout rate at 2.1%.",
                        "Lead time reduced to 5.6 days across key suppliers.",
                        "Ocean freight delivers the lowest cost per unit among ship modes.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Supply Chain Director",
                            "problem": "Need end-to-end visibility across cost, delivery, and inventory performance.",
                            "solution": "Executive dashboard with KPI cards and supply chain summary metrics.",
                        },
                        {
                            "stakeholder": "Procurement Manager",
                            "problem": "Must identify suppliers missing delivery commitments and cost targets.",
                            "solution": "Supplier scorecards and delivery commitment tracking views.",
                        },
                        {
                            "stakeholder": "Inventory Manager",
                            "problem": "Track stockout risk, turnover, and overstock by category.",
                            "solution": "Inventory turnover KPIs and stockout rate analysis by product.",
                        },
                        {
                            "stakeholder": "Logistics Manager",
                            "problem": "Compare ship modes, routes, and lead time bottlenecks.",
                            "solution": "Logistics performance views and on-time delivery by region.",
                        },
                        {
                            "stakeholder": "Finance Manager",
                            "problem": "Monitor supply chain cost trends and cost drivers over time.",
                            "solution": "Cost trend analysis and cost-by-category breakdown views.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard helped the business save time, reduce cost, and improve service level.",
                    "checklist": [
                        "Reduced supply chain cost by 8.7%",
                        "Improved on-time delivery by 4.3%",
                        "Reduced lead time to 5.6 days",
                        "Improved inventory turnover to 6.2x",
                        "Reduced manual reporting time by 70%",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform complex supply chain data into clear, decision-ready analytics.",
                    "bullets": [
                        "End-to-end supply chain visibility requires connecting orders, inventory, and logistics in one model.",
                        "Strong DAX and data modeling turn operational data into actionable KPIs leaders trust.",
                        "Dashboard design is about storytelling—not just displaying metrics.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 10M+ supply chain records",
                        "Built Star Schema data model",
                        "Created 50+ DAX measures and KPIs",
                        "Optimized Power BI performance",
                        "Integrated multiple data sources",
                        "Designed interactive drill-through pages",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "Kaggle Supply Chain Dataset",
                    "datasets": [],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "zillow",
        "title": "US Housing Price Trends & Market Insights for Smarter Decisions",
        "color": "#AFA9EC",
        "icon": "ZH",
        "preview_image": "images/projects/zillow-housing-executive-summary.png",
        "tags": ["Power BI", "Maps", "DAX", "Zillow ZHVI"],
        "summary": "Helps users compare housing prices, inventory, and regional trends to investigate market patterns more clearly.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Helps users compare markets and investigate housing price, inventory, and regional trends that matter for decisions.",
            "description": "Housing price and inventory signals are hard to compare when regional trends are scattered across reports. This market analytics experience organizes home prices, sales activity, inventory, and regional patterns into a clearer investigative view.",
            "hero_image": "images/projects/zillow-housing-executive-summary.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/us-housing-market-powerbi-dashboard"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Housing price and inventory signals are hard to compare when regional trends are scattered across reports.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "Which metros and states show the strongest price growth?",
                            "How are inventory and days on market trending over time?",
                            "Which property types drive the most sales volume?",
                            "Where are regional price differences most significant?",
                        ],
                    },
                    "goal": "Provide a housing market analytics experience that helps users compare regional patterns and investigate market changes.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from housing data preparation and modeling to dashboard design and stakeholder delivery.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate housing market insights and a dashboard leaders could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Standardized listings, census fields, and regional dimensions from multiple housing data providers.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema connecting sales, geography, property type, and calendar dimensions.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for median price, price per sq ft, inventory, days on market, and affordability.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built interactive visuals with maps, trend charts, drill-through pages, and executive-friendly layouts.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "A clean, executive-friendly dashboard with KPI scorecards, price trends, property type analysis, state comparisons, regional maps, and market summary tables—designed for clarity at a glance.",
                    "gallery": [
                        "images/projects/zillow-housing-executive-summary.png",
                        "images/projects/zillow-housing-state-comparison.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Leaders can now find answers in seconds instead of waiting for manual market reports.",
                    "insights": [
                        {"icon": "trend", "text": "Median home price increased 7.2% YoY"},
                        {"icon": "percent", "text": "Inventory declined 15.6% YoY"},
                        {"icon": "globe", "text": "California leads with $582K median price"},
                        {"icon": "people", "text": "Single family homes drive 63.1% of sales"},
                        {"icon": "trend", "text": "West region shows strongest growth at 9.8%"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "Automated narrative highlights surface the most important housing market patterns for leadership review.",
                    "executive_summary": [
                        "Median home price reached $412K, up 7.2% YoY.",
                        "West region leads growth at 9.8% YoY.",
                        "California has the highest median price at $582K.",
                        "Single family homes account for 63.1% of total sales.",
                        "Inventory fell to 2.6 months, indicating a seller's market.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Real Estate Investors",
                            "problem": "Need to identify high-growth markets and price momentum quickly.",
                            "solution": "Regional trend analysis and YoY growth comparison views.",
                        },
                        {
                            "stakeholder": "Realtors / Agents",
                            "problem": "Track local inventory, days on market, and pricing for client guidance.",
                            "solution": "Metro-level maps and inventory KPI dashboards.",
                        },
                        {
                            "stakeholder": "Lenders & Mortgage Analysts",
                            "problem": "Assess market risk and price stability across regions.",
                            "solution": "Median price trends, affordability index, and regional volatility indicators.",
                        },
                        {
                            "stakeholder": "Property Developers",
                            "problem": "Compare demand signals across property types and geographies.",
                            "solution": "Sales by property type and state-level price comparisons.",
                        },
                        {
                            "stakeholder": "Market Researchers",
                            "problem": "Monitor macro housing trends without manual data pulls.",
                            "solution": "Time-series price trends and executive summary metrics.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard saves time, improves market analysis, and gives leadership a shared view of housing performance.",
                    "checklist": [
                        "Reduced manual reporting time by 70%",
                        "Enabled faster market analysis",
                        "Improved regional comparison capability",
                        "Supported data-driven investment decisions",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform complex housing data into clear, decision-ready analytics.",
                    "bullets": [
                        "Understanding market questions before building visuals leads to better adoption.",
                        "Strong DAX and data modeling are what make housing KPIs reliable at scale.",
                        "Maps and regional comparisons are essential for real estate storytelling.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 10M+ housing records",
                        "Built Star Schema data model",
                        "Created 30+ DAX measures and KPIs",
                        "Optimized Power BI performance",
                        "Integrated geospatial visualizations",
                        "Designed interactive drill-through pages",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "Zillow Home Value Index (ZHVI)",
                    "datasets": [],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "uber",
        "title": "NYC FHV Performance Dashboard for Data-Driven Decisions",
        "color": "#F0997B",
        "icon": "UB",
        "preview_image": "images/projects/uber-fhv-executive-summary.png",
        "tags": ["Power BI", "DAX", "Power Query", "NYC Open Data"],
        "summary": "Explores when and where NYC FHV demand changes so users can investigate peak patterns, locations, and operating conditions.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Helps users explore where and when demand appears strongest and investigate the conditions that may explain those patterns.",
            "description": "Raw trip records show individual rides but do not clearly explain when, where, and under what conditions transportation demand changes. This transportation analytics experience organizes trip data into time, location, airport activity, and weekday-versus-weekend demand patterns.",
            "hero_image": "images/projects/uber-fhv-executive-summary.png",
            "actions": [
                {"label": "GitHub", "style": "default", "href": "https://github.com/jay-powerbi/nyc-fhv-powerbi-dashboard"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Raw trip records show individual rides but do not clearly explain when, where, and under what conditions transportation demand changes.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "Which hours and days generate the highest earnings?",
                            "Which pickup zones and boroughs drive the most trip volume?",
                            "How do airport trips compare to commuter and short trips?",
                            "Are trips, earnings, and distance improving over time?",
                        ],
                    },
                    "goal": "Provide an operational analytics and demand exploration experience that helps users investigate where and when demand appears strongest.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from TLC trip data preparation and modeling to dashboard design and stakeholder delivery.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Performance Optimization",
                        "Stakeholder Communication",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I followed a structured process to ensure accurate FHV insights and a dashboard operators could trust.",
                    "steps": [
                        {
                            "title": "Clean & Transform Data",
                            "text": "Removed duplicates, standardized zone and borough fields, and prepared refreshable trip datasets.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema connecting trips, zones, boroughs, calendar, and trip type dimensions.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed DAX measures for trips, gross earnings, distance, trip time, and earnings per trip.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built interactive visuals with heatmaps, borough breakdowns, zone rankings, and drill-through detail.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "A dark-themed, operator-friendly dashboard with KPI scorecards, trip trends, borough analysis, top pickup zones, time-of-day heatmaps, and trip type performance—designed for clarity at a glance.",
                    "gallery": [
                        "images/projects/uber-fhv-executive-summary.png",
                        "images/projects/uber-fhv-performance.png",
                        "images/projects/uber-fhv-driver-pay.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Drivers and analysts can now find answers in seconds instead of waiting for manual trip reports.",
                    "insights": [
                        {"icon": "trend", "text": "Friday & Saturday nights generate the most earnings"},
                        {"icon": "percent", "text": "Airport trips have the highest earnings per trip ($54.32)"},
                        {"icon": "globe", "text": "JFK Airport is the top earning pickup zone ($18.7M)"},
                        {"icon": "people", "text": "Manhattan has the highest trip volume (36.8%)"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "Automated narrative highlights surface the most important FHV performance patterns for leadership review.",
                    "executive_summary": [
                        "Total trips increased 12.6% YoY to 5.21M, driving 15.3% growth in gross earnings to $213.4M.",
                        "Airport trips average $54.32 per trip, significantly higher than commuter ($38.21) and short trips ($21.15).",
                        "Peak earnings occur Friday/Saturday nights between 6 PM and 2 AM.",
                        "JFK Airport is the top earning pickup zone, contributing $18.7M in gross earnings.",
                        "Average earnings per trip reached $40.96, up 2.4% YoY.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each stakeholder group gets targeted views that map directly to the decisions they need to make.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Drivers",
                            "problem": "Need to know when and where to drive for maximum earnings.",
                            "solution": "Time-of-day heatmaps, top pickup zones, and borough demand views.",
                        },
                        {
                            "stakeholder": "Fleet Operators",
                            "problem": "Optimize fleet deployment across boroughs and trip types.",
                            "solution": "Borough breakdown, trip type performance, and trend analysis.",
                        },
                        {
                            "stakeholder": "Business Analysts",
                            "problem": "Monitor FHV market trends and earnings performance over time.",
                            "solution": "Trips over time charts and YoY KPI scorecards.",
                        },
                        {
                            "stakeholder": "City Planners",
                            "problem": "Understand geographic demand concentration across NYC zones.",
                            "solution": "Zone rankings and borough distribution analysis.",
                        },
                        {
                            "stakeholder": "Policy Makers",
                            "problem": "Assess FHV activity patterns for regulatory and planning decisions.",
                            "solution": "Executive summary metrics and regional trip volume views.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard improves earnings optimization, fleet efficiency, and gives stakeholders a shared view of FHV performance.",
                    "checklist": [
                        "Increased driver earnings by optimizing time and zones",
                        "Improved fleet utilization and operational efficiency",
                        "Reduced manual reporting time by 70%",
                        "Provided a single source of truth for FHV performance",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to transform large-scale transportation data into clear, decision-ready analytics.",
                    "bullets": [
                        "Understanding driver and operator questions before building visuals leads to better adoption.",
                        "Aggregating high-volume trip data requires careful modeling for dashboard performance.",
                        "Time-of-day and zone views are essential for FHV earnings storytelling.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical achievements behind the dashboard build and performance optimization.",
                    "checklist": [
                        "Processed 20M+ FHV trip records",
                        "Built Star Schema data model",
                        "Created 35+ DAX measures and KPIs",
                        "Optimized Power BI performance",
                        "Integrated TLC Lookup Tables",
                        "Designed interactive drill-through pages",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "NYC TLC For-Hire Vehicle (FHV) Trip Records",
                    "datasets": ["January–March 2026"],
                },
                {
                    "icon": "database",
                    "label": "NYC Taxi Zone Lookup Table",
                    "datasets": [],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "federal-procurement",
        "title": "01 · U.S. Federal Procurement Dashboard for Telecom & Information Services",
        "color": "#3B82F6",
        "icon": "FP",
        "preview_image": "images/projects/federal-procurement-executive-summary.png",
        "tags": ["Power BI", "DAX", "Power Query", "USASpending.gov"],
        "summary": "Helps users explore federal procurement spending patterns across agencies, recipients, and contract types in the Telecom & Information Services sector.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Helps users investigate where federal procurement spending concentrates across agencies, recipients, and contract structures.",
            "description": "Federal procurement award data can be difficult to interpret when users need to understand which agencies spend the most, which recipients receive the largest awards, and how contract types and duration vary. This analytics experience organizes USASpending.gov contract awards for NAICS Sector 51 into focused executive, agency, and recipient views.",
            "hero_image": "images/projects/federal-procurement-executive-summary.png",
            "actions": [
                {"label": "Download PDF", "style": "primary", "href": "/static/files/us-federal-procurement-dashboard.pdf"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "Federal procurement award records show individual contracts, but raw award tables do not clearly reveal spending concentration, recipient patterns, or agency-level trends across the Telecom & Information Services sector.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "Which awarding agencies account for the largest share of contract spending?",
                            "Which recipients receive the highest award amounts?",
                            "How does average award amount change over time?",
                            "How is spending distributed across contract award types?",
                            "Where do award amount and contract duration patterns suggest deeper investigation?",
                        ],
                    },
                    "goal": "Provide an interactive federal procurement analytics experience that helps users explore agency, recipient, and contract-type spending patterns within NAICS Sector 51.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from USASpending.gov data preparation and modeling to dashboard design and narrative documentation.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Agency & Recipient Analysis Views",
                        "Dashboard Documentation",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I started with the spending questions users need answered, then structured the model and views around agency, recipient, and contract dimensions.",
                    "steps": [
                        {
                            "title": "Define Scope",
                            "text": "Focused the analysis on USASpending.gov prime contract awards for NAICS Sector 51 (Information), covering Fiscal Year 2025 across all federal awarding agencies.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema with Fact_Contracts connected to Dim_Agency, Dim_Recipient, Dim_Date, Dim_NAICS, and Dim_PSC.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed measures for total award amount, contract count, recipient count, average award, and average contract duration.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built executive, agency, and recipient analysis pages with filters for awarding agency, year, and NAICS code.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "An interactive procurement analytics experience with executive KPI views, agency spending breakdowns, recipient analysis, and documentation of scope and data sources.",
                    "gallery": [
                        "images/projects/federal-procurement-executive-summary.png",
                        "images/projects/federal-procurement-agency-analysis.png",
                        "images/projects/federal-procurement-recipient-analysis.png",
                        "images/projects/federal-procurement-about.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Users can move from high-level award totals into agency and recipient patterns that deserve closer review.",
                    "insights": [
                        {"icon": "trend", "text": "Total awards reached $72.78bn across approximately 2K contracts"},
                        {"icon": "people", "text": "607 recipients appear in the analyzed award set"},
                        {"icon": "globe", "text": "Department of Defense accounts for the highest agency award total at about $27bn"},
                        {"icon": "percent", "text": "Average contract duration is approximately 1,322 days"},
                        {"icon": "trend", "text": "Top recipients include major telecom and federal IT services providers"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "The dashboard surfaces the spending patterns most useful for investigating federal procurement concentration in NAICS 51.",
                    "executive_summary": [
                        "The analysis covers Telecom & Information Services contracts from USASpending.gov for Fiscal Year 2025.",
                        "Total award amount is $72.78bn across roughly 2K contracts and 607 recipients.",
                        "Department of Defense leads agency spending, followed by Transportation, Veterans Affairs, and Health and Human Services.",
                        "Delivery orders and definitive contracts account for a large share of award amount by contract type.",
                        "Recipient views help users compare award concentration and investigate duration versus award amount patterns.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each audience gets a path from high-level procurement totals to the agency or recipient details behind them.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Procurement Analysts",
                            "problem": "Need to understand which agencies and recipients drive spending concentration.",
                            "solution": "Executive and agency views with award totals, contract type mix, and recipient rankings.",
                        },
                        {
                            "stakeholder": "Market Researchers",
                            "problem": "Must compare federal IT and telecom award patterns across recipients and years.",
                            "solution": "Recipient analysis by NAICS code, year, and award amount versus contract duration.",
                        },
                        {
                            "stakeholder": "BI / Reporting Teams",
                            "problem": "Need a reusable model for multi-dimensional procurement analysis.",
                            "solution": "Star schema connecting contracts to agency, recipient, date, NAICS, and PSC dimensions.",
                        },
                        {
                            "stakeholder": "Policy & Oversight Reviewers",
                            "problem": "Need clear visibility into where federal spending concentrates within Sector 51.",
                            "solution": "Agency and sub-agency breakdowns with filters for year and award type.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard supports clearer investigation of federal procurement patterns without relying on raw award extracts alone.",
                    "checklist": [
                        "Makes agency and recipient spending concentration easier to explore",
                        "Supports investigation of contract type and duration patterns",
                        "Provides a reusable star-schema model for multi-dimensional award analysis",
                        "Documents data source, scope, and industry filter for transparent interpretation",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to turn public spending data into decision-oriented procurement analytics.",
                    "bullets": [
                        "Federal award analysis works best when agency, recipient, and contract-type questions are defined before visual design.",
                        "Star schema modeling keeps award fact tables flexible for multi-dimensional filtering.",
                        "Clear scope documentation helps users interpret open government data without overstating conclusions.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical choices behind the procurement analytics build.",
                    "checklist": [
                        "Used USASpending.gov public contract award data",
                        "Built Star Schema (Fact_Contracts + agency, recipient, date, NAICS, PSC dimensions)",
                        "Created KPIs for award totals, recipient counts, and contract duration",
                        "Designed executive, agency, and recipient analysis pages",
                        "Added filters for awarding agency, year, and NAICS code",
                        "Documented FY 2025 NAICS 51 scope and data source",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "USASpending.gov — U.S. Federal Contract Awards (Prime Awards)",
                    "datasets": ["Fiscal Year 2025", "NAICS Sector 51 (Information)"],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
    {
        "slug": "austin-procurement",
        "title": "02 · Austin Procurement Dashboard",
        "color": "#0f766e",
        "icon": "AP",
        "preview_image": "images/projects/austin-procurement-executive-summary.png",
        "tags": ["Power BI", "DAX", "Power Query", "City of Austin Open Data"],
        "summary": "Helps users explore municipal procurement spending across vendors, commodities, contracts, and purchase orders for the City of Austin.",
        "case_study": {
            "back_label": "Back to all projects",
            "hero_badge": "Business Case Study",
            "tagline": "Helps users investigate where City of Austin procurement spending concentrates across vendors, commodities, and contracts.",
            "description": "Municipal procurement data can be difficult to interpret when users need to understand which vendors receive the most spend, which commodities drive purchasing volume, and how contracted versus non-contracted purchases compare. This analytics experience organizes City of Austin open procurement data into focused executive, commodity, and contract views.",
            "hero_image": "images/projects/austin-procurement-executive-summary.png",
            "actions": [
                {"label": "Download PDF", "style": "primary", "href": "/static/files/austin-procurement-dashboard.pdf"},
            ],
            "sections": [
                {
                    "number": 1,
                    "title": "Business Problem, Questions, & Goal",
                    "icon": "target",
                    "icon_color": "#2563eb",
                    "intro": "City procurement records show individual purchase orders and contracts, but raw transaction tables do not clearly reveal vendor concentration, commodity spending patterns, or contract performance trends.",
                    "callout": {
                        "title": "Business Questions",
                        "entries": [
                            "Which vendors account for the largest share of procurement spending?",
                            "Which commodities and contracts drive the highest spend and purchase order volume?",
                            "How does spending trend across years?",
                            "What share of spending is contracted versus non-contracted?",
                            "Where do average purchase amounts suggest deeper investigation by commodity or vendor?",
                        ],
                    },
                    "goal": "Provide an interactive municipal procurement analytics experience that helps users explore vendor, commodity, and contract spending patterns for the City of Austin.",
                },
                {
                    "number": 2,
                    "title": "My Role",
                    "icon": "person",
                    "icon_color": "#0f9f7a",
                    "intro": "As the BI Developer, I owned end-to-end development—from City of Austin open data preparation and modeling to dashboard design and narrative documentation.",
                    "checklist": [
                        "Data Cleaning & Transformation",
                        "Data Modeling (Star Schema)",
                        "DAX Measures & KPIs",
                        "Dashboard Design (Power BI)",
                        "Commodity & Contract Analysis Views",
                        "Dashboard Documentation",
                    ],
                },
                {
                    "number": 3,
                    "title": "My Approach",
                    "icon": "gear",
                    "icon_color": "#7c6fd6",
                    "intro": "I started with the spending questions procurement teams need answered, then structured the model and views around vendor, commodity, contract, and time dimensions.",
                    "steps": [
                        {
                            "title": "Define Scope",
                            "text": "Focused the analysis on City of Austin open procurement and purchasing data covering vendors, commodities, contracts, and purchase orders across available years.",
                        },
                        {
                            "title": "Build Data Model",
                            "text": "Designed a star schema with a centralized procurement fact table connected to vendor, commodity, contract, and date dimensions.",
                        },
                        {
                            "title": "Create KPIs",
                            "text": "Developed measures for total spend, purchase order count, vendor count, average purchase amount, and total quantity.",
                        },
                        {
                            "title": "Design Dashboard",
                            "text": "Built executive, commodity, and contract analysis pages with filters for vendor, commodity, contract status, and year.",
                        },
                    ],
                },
                {
                    "number": 4,
                    "title": "The Dashboard",
                    "icon": "chart",
                    "icon_color": "#ef9f27",
                    "intro": "An interactive procurement analytics experience with executive KPI views, commodity spending breakdowns, contract analysis, and documentation of scope and data sources.",
                    "gallery": [
                        "images/projects/austin-procurement-executive-summary.png",
                        "images/projects/austin-procurement-commodity-analysis.png",
                        "images/projects/austin-procurement-contract-analysis.png",
                        "images/projects/austin-procurement-about.png",
                    ],
                },
                {
                    "number": 5,
                    "title": "Key Insights",
                    "icon": "insight",
                    "icon_color": "#e25555",
                    "intro": "Users can move from high-level procurement totals into vendor, commodity, and contract patterns that deserve closer review.",
                    "insights": [
                        {"icon": "trend", "text": "Total procurement spend reached $4.03bn across approximately 167K purchase orders"},
                        {"icon": "people", "text": "Roughly 6K vendors appear in the analyzed procurement set"},
                        {"icon": "globe", "text": "Texas Electric Cooperatives leads vendor spend at about $152M"},
                        {"icon": "percent", "text": "Contracted purchases account for 86.4% of total spend ($3.48bn)"},
                        {"icon": "trend", "text": "Transformers and application software rank among the highest-spend commodities"},
                    ],
                },
                {
                    "number": 6,
                    "title": "Executive Summary",
                    "icon": "spark",
                    "icon_color": "#2563eb",
                    "intro": "The dashboard surfaces the spending patterns most useful for investigating municipal procurement concentration in Austin.",
                    "executive_summary": [
                        "The analysis covers City of Austin procurement transactions from publicly available open data.",
                        "Total spend is $4.03bn across roughly 167K purchase orders and 6K vendors, with an average purchase amount of $24.12K.",
                        "Texas Electric Cooperatives, Silsbee Ford, and Sun Coast Resources lead vendor spending.",
                        "Bulk Fuels and critical materials supply contracts rank among the highest-spend agreements.",
                        "Commodity and contract views help users compare spend concentration, purchase order volume, and average purchase patterns.",
                    ],
                },
                {
                    "number": 7,
                    "title": "Stakeholder Value",
                    "icon": "users",
                    "icon_color": "#0f9f7a",
                    "intro": "Each audience gets a path from high-level procurement totals to the vendor, commodity, or contract details behind them.",
                    "stakeholder_rows": [
                        {
                            "stakeholder": "Procurement Analysts",
                            "problem": "Need to understand which vendors and contracts drive spending concentration.",
                            "solution": "Executive and contract views with spend totals, contract status mix, and vendor rankings.",
                        },
                        {
                            "stakeholder": "Finance & Budget Teams",
                            "problem": "Must compare commodity spending and purchase order activity across years.",
                            "solution": "Commodity analysis by spend, quantity, and average purchase amount with year filters.",
                        },
                        {
                            "stakeholder": "BI / Reporting Teams",
                            "problem": "Need a reusable model for multi-dimensional procurement analysis.",
                            "solution": "Star schema connecting procurement facts to vendor, commodity, contract, and date dimensions.",
                        },
                        {
                            "stakeholder": "Oversight & Policy Reviewers",
                            "problem": "Need clear visibility into contracted versus non-contracted purchasing patterns.",
                            "solution": "Contract status breakdowns with filters for vendor, commodity, and year.",
                        },
                    ],
                },
                {
                    "number": 8,
                    "title": "Business Impact",
                    "icon": "impact",
                    "icon_color": "#0f766e",
                    "intro": "The dashboard supports clearer investigation of municipal procurement patterns without relying on raw transaction extracts alone.",
                    "checklist": [
                        "Makes vendor and contract spending concentration easier to explore",
                        "Supports investigation of commodity spend versus purchase order volume",
                        "Provides a reusable star-schema model for multi-dimensional procurement analysis",
                        "Documents data source, scope, and analysis focus for transparent interpretation",
                    ],
                },
                {
                    "number": 9,
                    "title": "What I Learned",
                    "icon": "learn",
                    "icon_color": "#2563eb",
                    "intro": "This project strengthened my ability to turn municipal open data into decision-oriented procurement analytics.",
                    "bullets": [
                        "Municipal procurement analysis works best when vendor, commodity, and contract questions are defined before visual design.",
                        "Star schema modeling keeps procurement fact tables flexible for multi-dimensional filtering.",
                        "Clear scope documentation helps users interpret open government data without overstating conclusions.",
                    ],
                },
                {
                    "number": 10,
                    "title": "Technical Highlights",
                    "icon": "code",
                    "icon_color": "#7c6fd6",
                    "intro": "Key technical choices behind the Austin procurement analytics build.",
                    "checklist": [
                        "Used City of Austin Open Data public procurement and purchasing records",
                        "Built Star Schema (procurement fact table + vendor, commodity, contract, date dimensions)",
                        "Created KPIs for total spend, purchase orders, vendors, and average purchase amount",
                        "Designed executive, commodity, and contract analysis pages",
                        "Added filters for vendor, commodity, contract status, and year",
                        "Documented data source, scope, and analysis focus",
                    ],
                },
            ],
            "data_sources": [
                {
                    "icon": "database",
                    "label": "City of Austin Open Data — Procurement & Purchasing",
                    "datasets": ["Procurement transactions", "Vendors", "Commodities", "Contracts", "Purchase orders"],
                },
            ],
            "footer_cta": {
                "text": "Turning data into decisions that drive business forward.",
                "button_label": "Open to Opportunities",
                "button_href": "portfolio_opportunities",
            },
        },
    },
]


PORTFOLIO_PROJECT_MAP = {project["slug"]: project for project in PORTFOLIO_PROJECTS}

PORTFOLIO_PROJECT_ORDER = [
    "federal-procurement",
    "austin-procurement",
    "healthcare",
    "uber",
    "insurance",
    "retail",
    "supply-chain",
    "zillow",
]


def ordered_portfolio_projects():
    rank = {slug: index for index, slug in enumerate(PORTFOLIO_PROJECT_ORDER)}
    return sorted(PORTFOLIO_PROJECTS, key=lambda project: rank.get(project["slug"], len(rank)))
